server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: auth-service-css
              uri: http://localhost:8081
              predicates:
                  - Path=/css/**

            - id: auth-service-js
              uri: http://localhost:8081
              predicates:
                  - Path=/js/**

            - id: report-service
              uri: http://localhost:8082
              predicates:
                - Path=/report/**
            - id: research-service
              uri: http://localhost:8083
              predicates:
                - Path=/research/**
