server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: auth-service-css
          uri: http://localhost:8081
          predicates:
            - Path=/css/**

        - id: auth-service-js
          uri: http://localhost:8081
          predicates:
            - Path=/js/**

        - id: report-service
          uri: http://localhost:8083
          predicates:
            - Path=/report/**
          filters:
            - StripPrefix=1

        - id: research-service
          uri: http://localhost:8082
          predicates:
            - Path=/research/**
          filters:
            - StripPrefix=1

        - id: report-service-css
          uri: http://localhost:8083
          predicates:
            - Path=/report/css/**
          filters:
            - StripPrefix=1


        - id: report-service-js
          uri: http://localhost:8083
          predicates:
            - Path=/report/js/**
          filters:
            - StripPrefix=1

      forwarded:
        enabled: true